<?php

declare(strict_types=1);

namespace EzPhp\OPCache;

use DateTimeImmutable;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use SplFileInfo;

/**
 * Class Preloader
 *
 * Scans configured directories for PHP files and generates an OPcache preload script.
 *
 * Usage:
 *
 *   $config = new PreloadConfig(
 *       outputFile: '/var/www/html/preload.php',
 *       paths: ['/var/www/html/vendor/ez-php/framework/src'],
 *       excludePatterns: ['*Test.php', '*TestCase.php'],
 *   );
 *
 *   $preloader = new Preloader($config);
 *   $count = $preloader->generate();
 *
 * @package EzPhp\OPCache
 */
final class Preloader
{
    public function __construct(private readonly PreloadConfig $config)
    {
    }

    /**
     * Collect all PHP files from the configured paths, applying exclude patterns.
     *
     * Returns absolute file paths in lexicographic order for deterministic output.
     *
     * @return string[]
     */
    public function collect(): array
    {
        $files = [];

        foreach ($this->config->getPaths() as $path) {
            $realPath = realpath($path);

            if ($realPath === false || !is_dir($realPath)) {
                continue;
            }

            $iterator = new RecursiveIteratorIterator(
                new RecursiveDirectoryIterator($realPath, RecursiveDirectoryIterator::SKIP_DOTS),
            );

            /** @var SplFileInfo $file */
            foreach ($iterator as $file) {
                if ($file->getExtension() !== 'php') {
                    continue;
                }

                if ($this->isExcluded($file->getFilename())) {
                    continue;
                }

                $files[] = $file->getRealPath();
            }
        }

        sort($files);

        return array_values(array_unique($files));
    }

    /**
     * Generate the preload script and write it to the configured output file.
     *
     * Returns the number of files included in the generated script.
     *
     * @throws PreloadException When the output directory does not exist or the file cannot be written.
     */
    public function generate(): int
    {
        $files = $this->collect();
        $this->writeScript($files);

        return count($files);
    }

    /**
     * Check whether a filename matches any of the configured exclude patterns.
     */
    private function isExcluded(string $filename): bool
    {
        foreach ($this->config->getExcludePatterns() as $pattern) {
            if (fnmatch($pattern, $filename)) {
                return true;
            }
        }

        return false;
    }

    /**
     * Render and write the preload script to the output file.
     *
     * @param string[] $files Absolute paths of PHP files to include.
     *
     * @throws PreloadException When the output directory does not exist or writing fails.
     */
    private function writeScript(array $files): void
    {
        $outputFile = $this->config->getOutputFile();
        $outputDir = dirname($outputFile);

        if (!is_dir($outputDir)) {
            throw new PreloadException(
                sprintf('Output directory "%s" does not exist.', $outputDir),
            );
        }

        $generatedAt = (new DateTimeImmutable())->format('Y-m-d H:i:s');
        $count = count($files);

        $lines = [];
        $lines[] = '<?php';
        $lines[] = '';
        $lines[] = '// Auto-generated OPcache preload script.';
        $lines[] = sprintf('// Generated by ez-php/opcache at %s', $generatedAt);
        $lines[] = sprintf('// Total files: %d', $count);
        $lines[] = '// Usage: set opcache.preload=<this-file> in php.ini';
        $lines[] = '';

        if ($this->config->useRequireOnce()) {
            foreach ($files as $file) {
                $lines[] = sprintf("require_once '%s';", $file);
            }
        } else {
            $lines[] = "if (function_exists('opcache_compile_file')) {";
            foreach ($files as $file) {
                $lines[] = sprintf("    opcache_compile_file('%s');", $file);
            }
            $lines[] = '}';
        }

        $lines[] = '';

        $content = implode("\n", $lines);

        $result = file_put_contents($outputFile, $content);

        if ($result === false) {
            throw new PreloadException(
                sprintf('Failed to write preload script to "%s".', $outputFile),
            );
        }
    }
}
